// Mechanical summaries for catalog entries, paraphrased from the SR5 core
// rulebook's own rules text (Attributes p. 51-52, Qualities p. 71-87,
// Complex Forms p. 251-253, Rituals p. 296-298, Adept Powers p. 308-311,
// Mentor Spirits p. 320-324, Spells p. 283-294). The backend catalog itself
// carries no description field (see CatalogContract) — these are original,
// condensed paraphrases, not reproductions of the book's prose.

const ATTRIBUTE_DESCRIPTIONS: Record<string, string> = {
  body: 'Physical health and resiliency — how much damage you can take, how well you resist harm, and how fast you recover from poison and disease.',
  agility: 'Coordination, flexibility, and balance — the key attribute for landing hits in combat, and for sneaking, climbing, or any task needing a steady, dexterous touch.',
  reaction: 'Reflexes and awareness — how quickly you respond to danger, helping decide turn order in combat and your chances of dodging an attack.',
  strength: 'Raw physical power — how hard you hit, how much you can lift or carry, and how well you climb, run, and swim.',
  willpower: 'Mental toughness — your ability to push through adversity, resist spellcasting Drain, and stay upright after being hurt or intimidated.',
  logic: 'Rational, analytical thinking — used for repairing machinery, hacking, treating injuries, and resisting Drain as a hermetic mage.',
  intuition: 'Gut instinct — helps you notice danger, anticipate ambushes, and pick up a trail before your conscious mind catches up.',
  charisma: 'Force of personality — your persuasiveness and charm in social situations, and the attribute shamanic mages use to resist Drain.',
  edge: 'Raw luck — spent, not rolled, to buy specific game-changing effects like extra dice, a reroll, or shrugging off a critical glitch.',
  essence: 'A measure of your remaining humanity. Starts at 6 and is spent whenever you install cyberware or bioware; losses also drag down Magic and Resonance, and hitting 0 is fatal.',
  magic: 'How strong a spellcaster or adept you are. Sits at 0 for anyone without magical training, and fuels both spellcasting power and adept abilities.',
  resonance: 'A technomancer’s equivalent of Magic — the strength of their innate, toolless connection to the Matrix.',
}

const PATH_DESCRIPTIONS: Record<string, string> = {
  Mundane: 'No connection to Magic or Resonance. The character relies entirely on skills, gear, and augmentation.',
  Magician: 'Full sorcery and conjuring. Casts from the whole spell list, summons and binds spirits of a chosen tradition, and can perceive astrally at will.',
  MysticAdept: 'Splits Magic between spellcasting and Power Points, bought separately with Karma. Flexible, but thinner in both directions than a pure Magician or Adept.',
  Adept: 'No spellcasting. Every point of Magic buys Power Points spent on adept powers that sharpen the body and senses directly.',
  AspectedMagician: 'Access to only one magical skill group — Sorcery, Conjuring, or Enchanting. Cheaper in priority than a full Magician, at the cost of the other two.',
  Technomancer: 'A living connection to the Matrix in place of Magic. Resonance fuels sprites and complex forms instead of spirits and spells.',
}

const TRADITION_DESCRIPTIONS: Record<string, string> = {
  hermetic: 'Magic treated as a formal, learned science. Drain resists on Logic + Willpower, and spirits summoned are drawn from the elemental list.',
  shamanic: 'Magic practiced through relationship with totem spirits. Drain resists on Charisma + Willpower, and spirits summoned are drawn from the elemental list.',
}

const ASPECTED_VALUE_DESCRIPTIONS: Record<string, string> = {
  sorcery: 'Spells and rituals, cast and resisted exactly as a full Magician would — but no conjuring or enchanting.',
  conjuring: 'Summoning, binding, and banishing spirits — but no spellcasting or enchanting.',
  enchanting: 'Crafting foci, alchemical preparations, and other enchanted items — but no spellcasting or conjuring.',
}

const QUALITY_DESCRIPTIONS: Record<string, string> = {
  addiction: 'Chemical, technological, or behavioral dependency. Skipping a fix risks a dice pool penalty (worse at higher severity) on Mental or Physical tests until the craving is fed, and severe cases bleed into Social tests too.',
  allergy: 'An allergic reaction to a substance or condition. Exposure imposes a dice pool penalty on Physical tests (or worse — ongoing damage at the top end) for as long as symptoms last.',
  ambidextrous: 'No off-hand penalty — normally a −2 dice pool modifier for acting with your off-hand.',
  'analytical-mind': '+2 dice pool modifier to Logic tests for pattern recognition, evidence analysis, or puzzle-solving, and halves the time needed to work out a problem.',
  aptitude: 'Lets one skill be rated at 7 at character creation (above the normal cap of 6), and built up to 13 over time.',
  'astral-beacon': 'Your astral signature burns unusually bright and lasts twice as long, making you easy for astral trackers to find.',
  'astral-chameleon': 'Your astral signature is hard to detect and fades in half the normal time; assensing it suffers a −2 dice pool modifier.',
  'bad-luck': 'Once per game session, spending Edge backfires completely — the intended effect happens in reverse instead of helping you.',
  'bad-rep': 'Starts play with 3 points of Notoriety from a lasting bad reputation, removable only by confronting and resolving its source.',
  bilingual: 'Grants a second language at native fluency for free, on top of your normal language picks.',
  blandness: 'Nearly impossible to describe or recall. Raises the threshold to remember details about you by 1, and searches based on your description suffer a −2 dice pool modifier.',
  catlike: '+2 dice pool modifier to Sneaking tests.',
  'code-of-honor': 'You will not kill (or let others kill) a chosen group, with real complications when that’s tested — but the restraint earns bonus Karma.',
  codeblock: 'A specific Matrix action always trips you up — a −2 dice pool modifier whenever you attempt it.',
  codeslinger: '+2 dice pool modifier to one chosen Matrix action.',
  'combat-paralysis': 'Your first Initiative Score in a fight is halved, and you take a −3 dice pool modifier on Surprise Tests.',
  dependents: 'One or more people rely on you for support, slowing skill training by 50% and raising your lifestyle cost 10-30% depending on how demanding they are.',
  'distinctive-style': 'A memorable trait makes you easy to identify — anyone tracking or describing you gets a +2 dice pool modifier, though it also makes you a little easier for witnesses to recall correctly.',
  'double-jointed': '+2 dice pool modifier to Escape Artist tests, and lets you squeeze into tight spaces others can’t.',
  'elf-poser': 'A human cosmetically passing as an elf, avoiding social penalties for being human — until discovered.',
  'exceptional-attribute': 'Lets one attribute exceed its metatype maximum by 1 point — you still have to spend the normal points or Karma to actually raise it there.',
  'first-impression': '+2 dice pool modifier on Social tests during a first meeting with anyone; the bonus doesn’t apply to later encounters.',
  'focused-concentration': 'Lets you sustain one spell or complex form, up to a Force/Level equal to your rating, without the usual sustaining penalty.',
  gearhead: 'Boosts a piloted vehicle or drone’s Speed or Handling temporarily, plus a +2 dice pool modifier on difficult driving stunts.',
  gremlins: 'Reduces the number of 1s needed to glitch by 1 per rating (max 4) whenever you use a moderately sophisticated device — tech just fails around you.',
  guts: '+2 dice pool modifier to resist fear and intimidation, including magically induced fear.',
  'high-pain-tolerance': 'Ignore 1 box of damage per rating (max 3) when calculating wound penalties.',
  'home-ground': 'Grants a home-turf bonus on your chosen streets (pick one): reduced background count, friendly locals, +2 to Matrix tests on your host, or a +2 bonus tied to knowing the area.',
  'human-looking': 'A metahuman who reads as human to NPCs, sidestepping anti-metahuman social penalties.',
  incompetent: 'Total inability to use an entire skill group — treated as fully unaware, even for tasks most people take for granted.',
  indomitable: '+1 to a chosen Inherent Limit (Mental, Physical, or Social) per level, up to 3 levels total.',
  insomnia: 'Slows Stun damage recovery — failing an Intuition + Willpower test doubles the time it takes to heal, and delays your Edge refresh at the severe tier.',
  juryrigger: '+2 dice pool modifier for jury-rigging repairs, and lets you pull off temporary technical miracles a normal Mechanics test wouldn’t allow.',
  'loss-of-confidence': 'A skill you’re normally proud of now suffers a −2 dice pool modifier, and you lose the use of any specialization (and Edge) tied to it.',
  'low-pain-tolerance': 'Wound penalties kick in every 2 boxes of damage instead of every 3.',
  lucky: 'Lets your Edge attribute exceed its metatype maximum by 1 point — you still have to pay Karma to actually raise it there.',
  'magic-resistance': 'Adds resistance dice against spells per rating (max 4) — but it’s always on, so it also resists beneficial spells like Heal.',
  'mentor-spirit': 'Bonds you to a patron mentor spirit that grants specific bonuses (and expectations) tied to its nature; switching mentors later costs Karma.',
  'natural-athlete': '+2 dice pool modifier to Running and Gymnastics tests.',
  'natural-hardening': 'Grants 1 point of natural biofeedback filtering against Matrix biofeedback damage, stacking with tech-based filtering.',
  'natural-immunity': 'Immune to one chosen disease or toxin (a synthetic one costs more); doesn’t protect against magical afflictions.',
  'ork-poser': 'A human or elf cosmetically passing as an ork, avoiding social penalties for not being one — until discovered.',
  'photographic-memory': '+2 dice pool modifier to Memory tests.',
  prejudiced: 'Openly hostile to a chosen group — your own Social tests against them suffer a penalty, but they get an equal bonus against you, both scaling with how common the group is and how extreme your prejudice.',
  'quick-healer': '+2 dice pool modifier to all Healing tests made on you, including magical healing.',
  'resistance-to-pathogens-toxins': '+1 dice pool modifier to Resistance tests against disease and/or toxins, depending on the level purchased.',
  scorched: 'A past magical or Matrix trauma causes physical side effects (memory loss, blackouts, migraines, and the like) whenever you enter VR or slot a BTL, until treated.',
  'sensitive-system': 'Doubles Essence loss from cyberware; Awakened or technomancer variants instead risk extra Drain or Fading.',
  'simsense-vertigo': '−2 dice pool modifier to all tests while interacting with AR, VR, or simsense.',
  'sinner-layered': 'Carries a registered SIN (National, Criminal, Corporate Limited, or Corporate Born) — legal benefits come bundled with being trackable, taxed, and, at the harsher tiers, actively hunted or distrusted.',
  'social-stress': 'A specific trigger makes Leadership and Etiquette tests glitch more easily, and complicates ordinary social interaction.',
  'spirit-affinity': 'Grants an extra spirit service from one chosen spirit type, plus a +1 dice pool modifier to Binding tests for it.',
  'spirit-bane': 'A chosen spirit type actively hates you — they harass you, refuse favors, and prioritize attacking you; summoning or binding them suffers a −2 dice pool modifier.',
  toughness: '+1 dice pool modifier to Body for Damage Resistance tests.',
  uncouth: '−2 dice pool modifier resisting improper or impulsive social behavior; Social skills cost double to learn and Social skill groups can’t be learned at all.',
  uneducated: 'Treated as unaware in Technical, Academic, and Professional Knowledge skills you don’t already have, and learning them costs double.',
  'unsteady-hands': '−2 dice pool modifier to Agility tests when your shakes flare up; a failed test after a stressful encounter brings the symptoms back for the rest of the run.',
  'weak-immune-system': 'Increases the Power of any disease against you by +2 per Resistance Test.',
  'will-to-live': 'Grants 1 extra Damage Overflow box per rating (max 3), letting you survive more overflow damage before dying.',
}

const MENTOR_SPIRIT_DESCRIPTIONS: Record<string, string> = {
  bear: 'A protective healer who fights ferociously, even recklessly, for those in his care. Grants resistance-test bonuses, help with health magic or Rapid Healing, but risks going berserk when you or a ward is hurt.',
  cat: 'Stealthy, sly, and arrogant, toying with prey rather than striking cleanly. Grants Gymnastics/Infiltration or illusion-magic bonuses and Light Body, but you can’t finish a fight quickly unless you rein in the theatrics.',
  dog: 'A loyal, stubborn protector who tracks threats and never abandons a friend. Grants Tracking and detection-magic bonuses and sharpened senses, but you can’t leave a comrade behind without a fight.',
  dragonslayer: 'A heroic, fun-loving warrior who keeps every oath. Grants a social-skill bonus, combat-magic bonuses, and better aim and reflexes, but breaking a promise costs you dice until you make it right.',
  eagle: 'A proud, solitary guardian of nature’s purity, distrustful of technology and pollution. Grants Perception and air-spirit bonuses and sharper combat instincts, but leaves you allergic to pollutants.',
  'fire-bringer': 'A kind creator who devotes himself to others, sometimes to his own detriment. Grants Artisan/Alchemy or manipulation-magic bonuses and skill growth, but you can’t refuse a sincere request for help.',
  mountain: 'Rooted, stubborn, and nearly unmovable once a decision is made. Grants Survival and defensive-magic bonuses and extra magical armor, but changing your plan (or acting without one) takes real effort.',
  rat: 'A resourceful survivor who avoids open fights and strikes fast when cornered. Grants Sneaking and reagent-harvesting bonuses and toxin resistance, but pushes you to flee or hide first in a fight.',
  raven: 'A dark trickster who profits from chaos without causing it. Grants Con and manipulation-magic bonuses, stealth, and voice tricks, but tempts you toward exploiting others’ misfortune or pulling pranks.',
  sea: 'Unfathomable and moody — comforting one moment, dangerous the next, and fiercely protective of what she’s given. Grants Swimming and water-spirit bonuses and athletic boosts, but makes you reluctant to give anything away.',
  seducer: 'The incarnation of desire, exploiting weakness and inflaming others’ wants from a safe distance. Grants Con and illusion-magic bonuses and social skill tricks, but you struggle to resist temptation when it’s offered.',
  shark: 'A cold, relentless, wandering hunter who strikes without warning. Grants Unarmed Combat and combat-magic bonuses and a free lethal unarmed strike, but risks going berserk once blood is drawn.',
  snake: 'Wise and secretive, trading knowledge for a price and fighting only when needed. Grants Arcana and detection-magic bonuses and sharper social reads, but you can’t resist chasing a hint of hidden knowledge.',
  thunderbird: 'A primal, majestic storm made flesh, respected and feared in equal measure. Grants Intimidation and air-spirit bonuses and harder-hitting strikes, but you can’t let an insult go unanswered.',
  'wise-warrior': 'A disciplined tactician who fights from wisdom rather than bloodlust, bound by a warrior’s code. Grants Leadership/Instruction and combat-magic bonuses and sharper skill, but dishonorable behavior costs you dice until atoned for.',
  wolf: 'A loyal pack hunter, devoted to friends and family to the last. Grants Tracking and combat-magic bonuses and faster reflexes, but you can’t bring yourself to retreat from a fight.',
}

const ADEPT_POWER_DESCRIPTIONS: Record<string, string> = {
  'adrenaline-boost': 'Spends a bit of yourself for speed now — +2 Initiative Score per level for the current turn, paid back as Drain on the next.',
  'astral-perception': 'Lets you perceive the astral plane like a magician, becoming dual-natured while active — useful, but it opens you up to astral attacks too.',
  'attribute-boost': 'Briefly pushes one physical attribute (Agility, Body, Reaction, or Strength) above its normal maximum, at the cost of Drain once the boost wears off.',
  'combat-sense': 'An instinctive early-warning system — bonus dice on defense against ranged and melee attacks, plus a guaranteed shot at noticing a surprise attack coming.',
  'critical-strike': 'Hits harder with one chosen melee skill — a flat damage bonus that stacks with weapons and other adept powers.',
  'danger-sense': 'Sharpens your gut instinct for trouble, adding dice to Surprise Tests so ambushes catch you less flat-footed.',
  'enhanced-accuracy': 'Turns a chosen combat skill’s weapon into an extension of your body, adding to its effective Accuracy.',
  'enhanced-perception': 'Sharpens every sense at once — bonus dice on Perception and Assensing tests.',
  'improved-ability': 'Adds bonus dice to a single skill you already know, on top of its trained rating.',
  'improved-physical-attribute': 'Permanently pushes one physical attribute above its natural maximum — expensive, but it sticks.',
  'improved-potential': 'Raises one of your Inherent Limits (Physical, Mental, or Social), letting more of your hits actually count.',
  'improved-reflexes': 'Wired-reflexes-style speed from magic alone — extra Reaction and bonus Initiative Dice, though it can’t stack with tech that does the same thing.',
  'improved-sense': 'Grants a specific sensory upgrade (low-light vision, keen hearing, and the like) that your metatype wouldn’t normally have.',
  'killing-hands': 'Turns your bare hands into a lethal weapon, letting unarmed strikes deal Physical instead of Stun damage — and bypass some magical defenses.',
  kinesics: 'Complete control over your own body language and tells, making you much harder to read in a social confrontation.',
  'light-body': 'Adds reach to your jumps and a softer landing when you fall, at the cost of nothing but training.',
  'missile-parry': 'Lets you knock — or even catch — a slow-moving thrown or fired projectile out of the air.',
  'mystic-armor': 'Magically toughens your body, adding Armor that stacks with anything you’re wearing.',
  'natural-immunity': 'Bonus resistance dice against toxins and disease.',
  'pain-resistance': 'Pushes back the point where wound penalties start biting, letting you fight through more damage before it slows you down.',
  'rapid-healing': 'Speeds up natural recovery and makes any healing you receive — magical or mundane — more effective.',
  'spell-resistance': 'Bonus resistance dice against spells, rituals, and alchemical preparations aimed at you.',
  'traceless-walk': 'Moves without leaving a physical trace — no sound, no footprints, and much harder to track even by scent.',
  'voice-control': 'Total command over your own voice — mimicry, disguise, and a social edge whenever your voice does the talking.',
  'wall-running': 'Briefly defies gravity, letting you sprint up or across a vertical surface before you have to come back down.',
}

const RITUAL_DESCRIPTIONS: Record<string, string> = {
  'circle-of-healing': 'A group healing rite performed around an anchor — everyone inside the circle gets treated by the same casting.',
  'circle-of-protection': 'Raises a physical-and-astral barrier around an anchor, sealing out hostile spirits and mundane intrusion until something inside breaks it.',
  curse: 'Reaches an illusion spell across any distance through a physical piece of the target — no line of sight needed, just a material link.',
  homunculus: 'Animates an inanimate object into a semi-intelligent servant that obeys simple commands until the ritual ends.',
  'prodigal-spell': 'Lets a spotter’s eyes carry a combat spell to a target completely out of the caster’s own line of sight.',
  'remote-sensing': 'Extends a Detection spell through a spotter, letting the whole ritual team share what the spell’s subject perceives from anywhere.',
  renascence: 'Keeps an area manipulation spell running on its own for an extended time, without anyone needing to actively sustain it.',
  ward: 'Raises a lasting astral barrier around a warded space, blocking spirits and astral forms from passing through.',
  watcher: 'Summons a minor, obedient spirit-like servant born from the caster’s own mind to observe and report.',
}

const COMPLEX_FORM_DESCRIPTIONS: Record<string, string> = {
  cleaner: 'Scrubs a few points off your Overwatch Score, buying time before the corps notice what you’re doing.',
  'diffusion-of-attack': 'Weakens a target device’s Attack rating for as long as you sustain the form.',
  'diffusion-of-data-processing': 'Weakens a target device’s Data Processing rating for as long as you sustain the form.',
  'diffusion-of-firewall': 'Weakens a target device’s Firewall rating for as long as you sustain the form.',
  'diffusion-of-sleaze': 'Weakens a target device’s Sleaze rating for as long as you sustain the form.',
  editor: 'Lets you quietly rewrite the contents of a file you don’t own, as if you’d hacked it the normal way.',
  'infusion-of-attack': 'Boosts a target device’s Attack rating for as long as you sustain the form.',
  'infusion-of-data-processing': 'Boosts a target device’s Data Processing rating for as long as you sustain the form.',
  'infusion-of-firewall': 'Boosts a target device’s Firewall rating for as long as you sustain the form.',
  'infusion-of-sleaze': 'Boosts a target device’s Sleaze rating for as long as you sustain the form.',
  'pulse-storm': 'Floods the area with Resonance static, adding noise to every persona caught nearby.',
  puppeteer: 'Forces a target device to carry out one Matrix action of your choosing on its own.',
  'resonance-channel': 'Opens a private Resonance link to a device, cutting down the noise penalty of talking to it from a distance.',
  'resonance-spike': 'Sends a raw burst of destructive Resonance into a device, dealing Matrix damage with no chance to resist.',
  'resonance-veil': 'Cloaks your own persona’s presence, hiding you from casual notice on the grid.',
  'static-bomb': 'A burst of Resonance disruption that shakes off icons currently spotting you.',
  'static-veil': 'Keeps your Overwatch Score from climbing as fast while you stay hidden on a grid you don’t control.',
  stitches: 'Repairs Matrix damage on a sprite, patching its Resonance pattern back together.',
  tattletale: 'Deliberately raises a target’s Overwatch Score, drawing corp attention down on them instead of you.',
  'transcendent-grid': 'Briefly connects you to every grid at once, erasing the usual penalties for acting across grids.',
}

const SPELL_DESCRIPTIONS: Record<string, string> = {
  'acid-stream': 'Sprays a target with corrosive acid that eats through armor and flesh alike, dealing Physical damage.',
  agony: 'Illusion of excruciating pain — the target suffers the same penalties as real Physical and Stun damage, though no lasting harm remains once the spell ends.',
  'analyze-device': 'Reveals the hidden purpose and workings of a scanned device, and helps the caster operate it more effectively while the spell holds.',
  'analyze-magic': 'Analyzes a magical object or effect — a focus, preparation, ritual, or the like — to learn about whoever created it.',
  'analyze-truth': 'Lets the caster tell whether a statement spoken aloud is one the speaker genuinely believes to be true.',
  animate: 'Brings a single inanimate object to life, giving it rough, shambling movement under the caster’s control.',
  antidote: 'Boosts a poisoned target’s odds on their upcoming Toxin Resistance Test, cast in the moments right after exposure.',
  armor: 'Wraps the target in a field of magical energy that adds extra Armor against physical damage.',
  'ball-lightning': 'An area burst of lightning that scorches everyone caught in the blast.',
  blast: 'An area burst of raw kinetic force that batters everyone caught in it with Stun damage.',
  bugs: 'Illusion of countless bugs crawling and biting all over the target’s body, panicking and distracting them.',
  chaos: 'A storm of conflicting sensory static that overwhelms a target’s senses, affecting technology as well as minds.',
  'chaotic-world': 'An area version of Chaos, blanketing everyone and every sensor nearby in disorienting sensory noise.',
  clairaudience: 'Projects the caster’s hearing to a distant point, letting them listen in from afar.',
  clairvoyance: 'Projects the caster’s vision to a distant point, letting them see from afar.',
  clout: 'An invisible blow of psychokinetic force that stuns a single target.',
  'combat-sense': 'A sixth sense for danger that sharpens the target’s Reaction against surprise and incoming attacks.',
  confusion: 'Floods a target’s mind with distracting sensations, penalizing everything they try to do.',
  'control-actions': 'Seizes direct control of a target’s body, forcing it to carry out the caster’s commands.',
  'control-thoughts': 'Subtly commands a target’s mind so they believe the caster’s orders are their own idea.',
  'cure-disease': 'Helps an infected target’s body fight off an illness faster, though it doesn’t undo damage already done.',
  'death-touch': 'A touch-range strike of lethal magical energy that inflicts severe Physical damage.',
  'decrease-attribute': 'Magically weakens one of the target’s Physical or Mental attributes.',
  'detect-enemies': 'Senses living targets nearby who mean the caster harm.',
  'detect-enemies-extended': 'The extended-range version of Detect Enemies, sensing hostile intent from much farther away.',
  'detect-individual': 'Senses the presence of one specific, previously-met individual anywhere within range.',
  'detect-life': 'Senses all nearby living beings and roughly where they are.',
  'detect-life-extended': 'The extended-range version of Detect Life, sensing living beings from much farther away.',
  'detect-life-form': 'Senses all nearby members of one specific type of living creature.',
  'detect-life-form-extended': 'The extended-range version of Detect Life Form, sensing that creature type from much farther away.',
  'detect-magic': 'Senses nearby foci, active spells, wards, lodges, rituals, and spirits.',
  'detect-magic-extended': 'The extended-range version of Detect Magic, sensing magical activity from much farther away.',
  'detect-object': 'Senses all nearby objects of one specific type and roughly where they are.',
  detox: 'Purges the lingering side effects of a poison or drug already in the target’s system.',
  entertainment: 'Conjures an obviously fake but captivating illusion, purely for an audience’s enjoyment.',
  fireball: 'An area burst of flame that scorches and burns everyone caught in the blast.',
  flamethrower: 'A single-target jet of flame that burns and can ignite what it touches.',
  fling: 'Psychokinetically hurls an object at a target like an improvised thrown weapon.',
  heal: 'Magically closes physical wounds, restoring boxes of Physical damage.',
  hush: 'Dampens sound magically over an area, muffling sonic attacks and mundane noise for living targets.',
  'ice-sheet': 'Coats an area in slick ice, risking a fall for anyone crossing it and forcing vehicles to test for control.',
  ignite: 'Sets a target smoldering and eventually ablaze, whether living or not.',
  'improved-invisibility': 'Renders the target unseeable to normal and augmented vision, including technological sensors.',
  'increase-attribute': 'Magically boosts one of the target’s Physical or Mental attributes.',
  'increase-reflexes': 'Speeds up the target’s reactions, adding to their Initiative Score and Initiative Dice.',
  influence: 'Plants a single post-hypnotic suggestion in the target’s mind that they act on as if it were their own idea.',
  invisibility: 'Renders the target unseeable to normal and augmented vision, though not to technological sensors.',
  knockout: 'A touch-range spell that knocks a target unconscious with Stun damage.',
  levitate: 'Telekinetically lifts and moves a person or object through the air.',
  light: 'Conjures a mobile point of magical light to push back darkness.',
  'lightning-bolt': 'A single-target bolt of lightning that deals Physical electrical damage.',
  'magic-fingers': 'Conjures an invisible telekinetic hand that can manipulate objects and perform simple tasks at a distance.',
  'mana-barrier': 'Raises an invisible magical wall that blocks spirits, foci, and other astral or magical traffic.',
  manaball: 'An area burst of pure mana that deals Physical damage to every living thing caught in it.',
  manabolt: 'A single-target bolt of pure mana that deals Physical damage.',
  mask: 'Disguises the target’s physical appearance, voice, and scent as someone or something else.',
  'mass-agony': 'An area version of Agony, wracking everyone caught in it with the illusion of terrible pain.',
  'mass-animate': 'Brings multiple inanimate objects to life at once, all shambling under the caster’s control.',
  'mass-confusion': 'An area version of Confusion, overwhelming everyone caught in it with distracting sensations.',
  'mind-probe': 'Telepathically reads a target’s mind — from surface thoughts up to deeply buried memories, given enough hits.',
  mindlink: 'Opens a two-way mental link between the caster and a willing subject to exchange thoughts and images.',
  'mob-control': 'An area version of Control Actions, letting the caster puppet the bodies of everyone caught in it.',
  'mob-mind': 'An area version of Control Thoughts, letting the caster command the minds of everyone caught in it.',
  oxygenate: 'Oxygenates the target’s blood, helping them resist suffocation and even breathe underwater.',
  phantasm: 'Conjures a convincing illusion of any object, creature, or scene the caster has seen before, affecting only living minds.',
  'physical-barrier': 'Raises a solid, translucent force wall that blocks movement and most attacks.',
  'physical-mask': 'Disguises the target’s appearance in a way that fools technology as well as onlookers.',
  poltergeist: 'Whirls loose debris around an area, battering everyone inside with flying junk.',
  powerball: 'An area burst of destructive magical energy that deals Physical damage.',
  powerbolt: 'A single-target bolt of destructive magical energy that deals Physical damage.',
  prophylaxis: 'Boosts the target’s resistance to infection, drugs, and toxins — including beneficial ones.',
  punch: 'A touch-range blow of psychokinetic force that stuns the target.',
  'resist-pain': 'Numbs the target to the pain of their injuries, removing wound penalties without healing the damage itself.',
  shadow: 'Conjures a globe of magical darkness over an area.',
  shatter: 'A touch-range strike of destructive force that deals severe Physical damage.',
  silence: 'Dampens sound over an area, muffling sonic attacks and mundane noise for both living and technological targets.',
  stabilize: 'Stabilizes a dying character with overflow damage, buying time before they die of their wounds.',
  stealth: 'Muffles the target’s own movement noise, though whatever they touch can still make sound.',
  stunball: 'An area burst of magical energy that deals Stun damage to everyone caught in it.',
  stunbolt: 'A single-target bolt of magical energy that deals Stun damage.',
  swarm: 'Illusion of bugs crawling over the target’s whole body, sapping their Initiative each turn it’s sustained.',
  'toxic-wave': 'An area spray of corrosive acid that burns everyone and everything caught in it.',
  'trid-entertainment': 'A physical version of Entertainment — an obvious illusion that both people and technology can perceive.',
  'trid-phantasm': 'A physical version of Phantasm — a convincing illusion that fools technology as well as living minds.',
}

const SPELL_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  combat: 'Combat spells inflict direct damage on a target when the spell connects.',
  illusion: 'Illusion spells deceive a target’s senses or mind rather than causing direct physical harm.',
  detection: 'Detection spells reveal information — locations, auras, thoughts, or the presence of specific things.',
  manipulation: 'Manipulation spells alter a target, object, or the environment’s physical or mental state.',
  health: 'Health spells heal, harm gradually, or otherwise adjust the condition of a living body.',
}

const SPELL_TYPE_DESCRIPTIONS: Record<string, string> = {
  mana: 'As a mana spell, it affects the target’s mind or aura directly and ignores mundane physical barriers.',
  physical: 'As a physical spell, it manifests physically and can be blocked or deflected like a mundane effect.',
}

const SKILL_DOMAIN_DESCRIPTIONS: Record<string, string> = {
  active: 'A conventional, trainable skill — usable untrained at a penalty in most cases.',
  magical: 'A magical skill available only to characters with access to Magic.',
  resonance: 'A Matrix skill available only to technomancers, powered by Resonance rather than hardware.',
}

const AUGMENTATION_DESCRIPTIONS: Record<string, string> = {
  'commlink-implanted': 'An implanted commlink with a built-in sim module — popular with corporate operatives who don’t want to carry one.',
  'control-rig': 'Lets you jump into a rigged vehicle or drone and control it directly, adding your rating to piloting tests, Handling, and Speed.',
  'cortex-bomb-kink': 'An illegal coercive implant that can be remotely detonated to disable specific headware or cause targeted brain trauma.',
  'cortex-bomb-microbomb': 'An illegal coercive implant powerful enough to kill its bearer when detonated.',
  'cortex-bomb-area-bomb': 'An illegal coercive implant that kills its bearer and detonates like a fragmentation grenade over the surrounding area.',
  'cyberdeck-implanted': 'A full cyberdeck built into your body — a favorite of deckers who don’t want to carry external hardware.',
  datajack: 'A direct neural interface port with a retractable cable, letting you plug straight into electronic devices.',
  'data-lock': 'Turns you into a walking, tamper-resistant data safe — you can carry protected data but can’t read it yourself.',
  'olfactory-booster': 'A cybernetic sniffer that massively enhances your sense of smell, adding to scent-based Perception tests.',
  'simrig-implanted': 'An implanted simrig that records sensory data for later playback or resale.',
  skilljack: 'Interprets knowsofts and linguasofts (and, with skillwires, activesofts) so you can use them as your own trained skills.',
  'taste-booster': 'Enhances your sense of taste, adding to taste-based Perception tests and letting you experience AR/VR “taste tracks.”',
  'tooth-compartment': 'A hollow tooth for smuggling tiny items, or a breakable trigger for a linked effect like an alarm or a hidden dose of poison.',
  'ultrasound-sensor-implanted': 'An implanted ultrasound sensor that replaces your normal vision with active or passive sonar.',
  'voice-modulator': 'Gives you perfect pitch, vocal range, and the ability to imitate recorded voices — adds to Impersonation tests.',
  cybereyes: 'Full cybernetic eye replacements with a built-in image link and camera, plus capacity for further vision upgrades.',
  'flare-compensation-implanted': 'An implanted version of flare compensation, protecting your vision from sudden bright light.',
  'image-link-implanted': 'An implanted receiver for AR image feeds sent directly to your eyes.',
  'low-light-vision-implanted': 'An implanted version of low-light vision, letting you see clearly in dim conditions.',
  'retinal-duplication': 'An illegal implant that can be loaded with a recorded retina scan to fool retinal scanners.',
  'smartlink-implanted': 'An implanted smartlink for smartgun-equipped weapons — more effective than an external smartlink device.',
  'thermographic-vision-implanted': 'An implanted version of thermographic vision, letting you see heat signatures.',
  'vision-enhancement-implanted': 'An implanted general vision-quality upgrade.',
  'vision-magnification-implanted': 'An implanted zoom lens for your eyes.',
  cyberears: 'Full cybernetic ear replacements with omni-directional hearing and sound link, plus capacity for further audio upgrades.',
  'audio-enhancement-implanted': 'An implanted version of audio enhancement, sharpening your hearing.',
  'balance-augmenter': 'Enhances your inner ear’s balance mechanism, adding a bonus die to balance-related tests like climbing or landing a jump.',
  'damper-implanted': 'Protects your hearing from sudden loud noises and sonic attacks like flashbangs.',
  'select-sound-filter-implanted': 'An implanted sound filter that can selectively mute chosen frequencies or sounds.',
  'sound-link-implanted': 'Plays audio directly into your cyberears — the auditory counterpart to image link.',
  'spatial-recognizer-implanted': 'An implanted spatial recognizer aiding navigation and orientation.',
  'bone-lacing-plastic': 'Reinforces your skeleton with plastic lattice, adding a little Body, Armor, and unarmed damage.',
  'bone-lacing-aluminum': 'Reinforces your skeleton with aluminum lattice — more Body, Armor, and unarmed damage than plastic, at a higher cost.',
  'bone-lacing-titanium': 'Reinforces your skeleton with titanium lattice — the strongest bone lacing option, at real Essence and nuyen cost.',
  'dermal-plating': 'Hard plates bonded to your skin add visible bonus Armor, but can’t be combined with other skin-based armor like orthoskin.',
  'fingertip-compartment': 'A hidden compartment in a hollowed-out fingertip for smuggling micro-sized items.',
  'grapple-gun-implanted': 'An implanted grapple gun — no rope storage, but you can attach an external line before firing.',
  'internal-air-tank': 'A pressurized air reserve replacing part of a lung, letting you hold your breath for hours and resist inhaled toxins.',
  'muscle-replacement': 'Vat-grown synthetic muscle and skeletal reinforcement that boosts both Strength and Agility.',
  'reaction-enhancers': 'Superconducting spinal implants that add directly to your Reaction (and Initiative).',
  skillwires: 'Neuromuscular controllers that let you actually perform activesofts at full rating through a skilljack, not just as Knowledge.',
  'smuggling-compartment': 'A hollowed-out cavity (ribs, hip, shoulder blade) for smuggling small items past a body search.',
  'wired-reflexes': 'An invasive neural and adrenal overhaul that adds Reaction and bonus Initiative Dice when activated.',
  'obvious-cyberlimb-full-arm': 'A full obvious cybernetic arm — visibly mechanical, with base Strength and Agility of 3 and room for enhancements.',
  'obvious-cyberlimb-full-leg': 'A full obvious cybernetic leg — visibly mechanical, with base Strength and Agility of 3 and room for enhancements.',
  'obvious-cyberlimb-hand-foot': 'An obvious cybernetic hand or foot replacement, visibly mechanical.',
  'obvious-cyberlimb-lower-arm': 'An obvious cybernetic lower arm and hand, visibly mechanical.',
  'obvious-cyberlimb-lower-leg': 'An obvious cybernetic lower leg and foot, visibly mechanical.',
  'obvious-cyberlimb-torso': 'An obvious cybernetic torso shell rather than a full replacement, visibly mechanical.',
  'obvious-cyberlimb-skull': 'An obvious cybernetic skull shell rather than a full replacement, visibly mechanical.',
  'synthetic-cyberlimb-full-arm': 'A full synthetic cybernetic arm disguised as a natural limb — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-full-leg': 'A full synthetic cybernetic leg disguised as a natural limb — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-hand-foot': 'A synthetic cybernetic hand or foot disguised as natural — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-lower-arm': 'A synthetic cybernetic lower arm and hand disguised as natural — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-lower-leg': 'A synthetic cybernetic lower leg and foot disguised as natural — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-torso': 'A synthetic cybernetic torso shell disguised as natural — harder to spot, but obvious to the touch.',
  'synthetic-cyberlimb-skull': 'A synthetic cybernetic skull shell disguised as natural — harder to spot, but obvious to the touch.',
  'cybergun-hold-out-pistol': 'A cybernetic gun built into your arm or hand, firing a hold-out pistol round from a hidden internal magazine.',
  'cybergun-light-pistol': 'A cybernetic gun built into your arm, firing light pistol rounds from a hidden internal magazine.',
  'cybergun-machine-pistol': 'A cybernetic gun built into your arm, firing machine-pistol rounds with burst capability from a hidden internal magazine.',
  'cybergun-heavy-pistol': 'A cybernetic gun built into your arm, firing heavy pistol rounds from a hidden internal magazine.',
  'cybergun-submachine-gun': 'A cybernetic submachine gun built into your arm, firing automatic bursts from a hidden internal magazine.',
  'cybergun-shotgun': 'A cybernetic shotgun built into your arm, firing from a hidden internal magazine.',
  'cybergun-grenade-launcher': 'A cybernetic grenade launcher built into your arm, firing from a hidden internal magazine.',
  'hand-blade-retractable': 'A retractable blade concealed in the hand, deployable by muscle flexture, nerve impulse, or wireless signal.',
  'hand-razors-retractable': 'Short retractable blades hidden beneath the fingernails or replacing them entirely.',
  'spurs-retractable': 'One to three retractable blades or spikes that extend from the wrist or knuckles.',
  'shock-hand': 'A shock glove built into the palm, delivering an electrical jolt to anything it touches.',
  'adrenaline-pump': 'Floods your system with concentrated adrenaline on demand, letting you ignore injury and stay conscious — at the cost of a Stun crash once it wears off.',
  'bone-density-augmentation': 'Increases bone density and tensile strength, adding to Body for damage resistance and to unarmed damage.',
  'cats-eye': 'Vat-grown feline eyes that grant low-light vision — incompatible with cybernetic eye replacements.',
  'enhanced-articulation': 'Smoother joints and tendons that improve Escape Artist tests and raise your Physical limit.',
  'muscle-augmentation': 'Woven muscle cabling that adds directly to your Strength.',
  'muscle-toner': 'Increased muscle elasticity that adds directly to your Agility.',
  orthoskin: 'A web of biofibers under the skin that functions as nearly invisible personal armor.',
  'pathogenic-defense': 'An enhanced spleen that adds to your Disease Resistance Tests.',
  'platelet-factories': 'Accelerated blood clotting that reduces incoming Physical damage by a box whenever you take a serious hit.',
  'skin-pocket': 'A hidden, nerveless flap of skin used to conceal a small object — the bioware equivalent of a smuggling compartment.',
  'suprathyroid-gland': 'A supercharged thyroid that boosts Agility, Body, Reaction, and Strength — at the cost of needing to eat twice as much.',
  symbiotes: 'Tailored micro-organisms in your bloodstream that boost your natural and magical healing.',
  synthacardium: 'An enhanced heart and cardiovascular system that adds to Athletics-group skill tests.',
  'tailored-pheromones': 'Subtly influential pheromones that boost Acting and Influence tests at close range, plus your own Social limit.',
  'toxin-extractor': 'An enhanced liver that adds to your Toxin Resistance Tests.',
  'tracheal-filter': 'Filters airborne impurities before they reach your lungs, adding to resistance against inhaled toxins.',
  'cerebral-booster': 'Augmented brain tissue that adds directly to your Logic attribute.',
  'damage-compensators': 'Nerve-pathway cutoffs that let you ignore a number of damage boxes when calculating injury penalties.',
  'mnemonic-enhancer': 'Enhanced memory centers that boost Knowledge, Language, and memory-related tests, plus your Mental limit.',
  'pain-editor': 'Filters out pain entirely, letting you ignore injury modifiers and stay conscious through Stun overflow — at the cost of some tactile sense and Intuition.',
  'reflex-recorder': 'Grown neural tissue wired to a specific physical skill, adding a point to its rating.',
  'sleep-regulator': 'Lets you function on just three hours of sleep a night and stay awake much longer before fatigue sets in.',
  'synaptic-booster': 'Broadened spinal nerve pathways that boost Reaction and grant bonus Initiative Dice.',
}

const AUGMENTATION_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  'basic-bioware': 'Grown biological augmentation. Costs less Essence than cyberware of similar effect, but is pricier and rarer.',
  bodyware: 'Cyberware installed in the torso or body for general enhancement.',
  'cultured-bioware': 'Bioware grown from the recipient’s own cells — the gentlest option on Essence, and priced accordingly.',
  cyberlimb: 'A full cybernetic limb replacement, customizable with its own attribute ratings.',
  earware: 'Cyberware installed in the ear for hearing-related enhancement.',
  eyeware: 'Cyberware installed in the eye for vision-related enhancement.',
  headware: 'Cyberware installed in the skull for cognitive or sensory enhancement.',
  'implant-weapon': 'A weapon built directly into the character’s own body.',
}

const VEHICLE_DESCRIPTIONS: Record<string, string> = {
  'harley-davidson-scorpion': 'A classic, heavy chromed road hog built for intimidation — popular with go-gangers and tough enough for combat biking.',
  'horizon-flying-eye': 'A spherical, eyeball-sized flying minidrone that rolls on the ground but needs to fly over obstructions.',
  'dodge-scoot': 'A cheap, fuel-efficient electric scooter — compact, but hardly a status symbol.',
  'yamaha-growler': 'A durable off-road bike popular with thrill seekers, wilderness buffs, and light-freight smugglers.',
  'suzuki-mirage': 'A fast, sleek Japanese racing bike popular with go-gangers and combat bikers.',
  'chrysler-nissan-jackrabbit': 'A cheap, ubiquitous electric subcompact — the anonymous, unflashy choice.',
  'honda-spirit': 'A sleek three-wheeled electric two-seater popular with commuting sprawl dwellers.',
  'hyundai-shin-hyung': 'A cheap, fast four-door sports sedan popular with street racers, tuners, and corp youth showing off.',
  'eurocar-westwind-3000': 'A sleek, classic turbo-charged sportscar mixing luxury and performance — a dream car for most runners.',
  'ford-americar': 'An affordable, reliable four-door family sedan — economical, not fast or flashy.',
  'sk-bentley-concordat': 'A stylish, stately luxury sedan and unmistakable status symbol.',
  'mitsubishi-nightsky': 'A decadent, secure, high-tech armored limousine built for corp executives and media stars.',
  'toyota-gopher': 'A classic, low-maintenance pickup with great off-road suspension and a loyal following.',
  'gmc-bulldog-step-van': 'A capacious, armored delivery van favored by shippers, security agencies, and heavy mob crews alike.',
  'rover-model-2072': 'A big, powerful luxury van and status symbol, popular with discreet security details.',
  'ares-roadmaster': 'A legitimately-purchasable armored car with tank-like speed and handling that shrugs off small arms fire and grenades.',
  'samuvani-criscraft-otter': 'A well-rounded, general-purpose mid-size boat for pleasure boating, fishing, and light hauling.',
  'yongkang-gala-trinity': 'A small, fast smuggler’s speedboat, often built disposably around its cargo.',
  'morgan-cutlass': 'A commonly seen patrol boat with heavy manually-operated weapon mounts and a high-quality sensor suite.',
  'proteus-lamprey': 'An underwater sea-sled for inspection and transport, with riding positions for scuba-equipped passengers and a drone rack.',
  'vulkan-electronaut': 'A cheap two-person mini-sub used for patrol, reconnaissance, and resupply runs.',
  'artemis-nightwing': 'An older-model stealthy ultra-light aircraft with a quiet electric motor, popular for stealth insertions and smuggling.',
  'cessna-c750': 'A light, affordable dual-prop civilian plane for passengers, cargo, or surveillance.',
  'renault-fiat-fokker-tundra-9': 'An amphibious jet for heavy cargo and personnel that doesn’t need an airfield to land.',
  'ares-dragon': 'A versatile, solidly-built cargo helicopter used in urban and remote areas, sometimes as a gunship/troop transport.',
  'nissan-hound': 'A bleeding-edge military transport helicopter also popular with corporate security’s rapid response forces.',
  'northrup-wasp': 'A one-man rotorcraft built for police and corporate security response.',
  'ares-venture': 'A small, cheap light attack vehicle popular with smugglers, used for cargo, passenger, or patrol duty.',
  'gmc-banshee': 'A lightning-fast, supersonic aircraft — the iconic combat “t-bird” with real armor and armament.',
  'federated-boeing-commuter': 'A tilt-wing passenger shuttle aircraft ferrying corporate workers between aerospaceports.',
  'shiawase-kanmushi': 'A tiny four-legged bug-crawler drone that’s hard to tell from a real insect, but very fragile.',
  'sikorsky-bell-microskimmer': 'A quiet, durable disc-shaped microdrone smaller than a frisbee that can even skim over water.',
  'mct-fly-spy': 'An insect-sized drone that flies higher than most, ideal for shadowing people unnoticed.',
  'aztechnology-crawler': 'A small, efficient crawler drone that easily handles stairs and rough terrain.',
  'lockheed-optic-x2': 'A stealthy VSTOL drone the size of a folded cyberdeck, hard to detect by radar, visual, or audio.',
  'ares-duelist': 'An anthropomorphic walker drone with blade-arms, disguised to be mistaken for a metahuman guard.',
  'gm-nissan-doberman': 'A tracked perimeter-patrol drone with a standard weapon mount for day-or-night security duty.',
  'mct-nissan-roto-drone': 'A simple, highly modular rotor-wing drone built for easy customization.',
  'cyberspace-designs-dalmatian': 'A large, robust VTOL recon drone used by police for urban surveillance and patrol.',
  'steel-lynx': 'A hardened four-wheeled-leg ground combat drone with a heavy weapon mount.',
}

const WEAPON_DESCRIPTIONS: Record<string, string> = {
  'combat-axe': 'A two-handed tungsten-alloy axe, single- or double-bladed, with a concealed spring-loaded thrusting point.',
  'combat-knife': 'A long, KA-BAR-style fighting knife with a blacked-out blade and an armor-piercing chisel point.',
  'forearm-snap-blades': 'External retractable blades hidden in a forearm sheath, deployed by wireless signal or muscle movement.',
  katana: 'The legendary two-handed samurai sword — a shadowrunner cliché that’s still plenty dangerous.',
  knife: 'A basic all-purpose street cutter, cheap and unremarkable, favored by the poor, desperate, or cautious as a backup.',
  'pole-arm': 'A blade on a long haft — hard to conceal, but keeps attackers at a distance.',
  'survival-knife': 'A fine dual-edged blade with a GPS monitor, mini-multitool, and light built into the handle.',
  sword: 'A sharp, heavy one-handed blade in many styles — not as formidable as a katana, but far easier to hide.',
  club: 'A generic blunt weapon — axe handle, bat, wrench, crowbar, or anything else heavy and swingable.',
  'extendable-baton': 'A telescoping club that collapses for easy concealment and extends with a flick of the wrist or a wireless signal.',
  sap: 'A small, springy concealable club or flexible leather-wrapped weight, built for hiding.',
  staff: 'A large, heavy stick popular with magicians for its traditional look.',
  'stun-baton': 'A standard riot-control weapon dealing electrical shock damage, rechargeable over ten charges.',
  'telescoping-staff': 'A metal-and-composite staff that collapses for concealment and locks open with a twist or a wireless signal.',
  knucks: 'Fist-load weapons like brass knuckles or densiplast-lined gloves that boost the impact of an unarmed punch.',
  'monofilament-whip': 'An iconic, terrifying monofilament line that cuts through bone and armor — dangerous to the wielder too if it glitches.',
  'shock-gloves': 'Electrically insulated gloves that discharge a shock into anything they touch or punch.',
  bow: 'A traditional or modern compound bow — archaic, hacker-proof, and scaled to the wielder’s Strength.',
  'crossbow-light': 'A light crossbow with an automatic reloading magazine.',
  'crossbow-medium': 'A medium crossbow with an automatic reloading magazine.',
  'crossbow-heavy': 'A heavy crossbow with an automatic reloading magazine, hitting harder than its lighter cousins.',
  'throwing-knife': 'Aerodynamically balanced throwing blades — knives, spikes, darts, kunai, or shuriken.',
  'defiance-ex-shocker': 'A heavy-duty wired taser firing up to four darts, powerful enough to also work as a melee stun weapon.',
  'yamaha-pulsar': 'A wireless-dart taser — slightly weaker than the EX Shocker, but faster-firing and cable-free.',
  'fichetti-tiffani-needler': 'A stylish flechette-only hold-out pistol with a wireless color-changing coating.',
  'streetline-special': 'A small, lightweight composite hold-out pistol that’s hard for magnetic scanners to detect.',
  'walther-palm-pistol': 'A classic double-barreled derringer — packs a punch for its size, but only holds two rounds.',
  'ares-light-fire-75': 'A special-operator’s pistol with an integral silencer and smartgun system.',
  'ares-light-fire-70': 'One of the most common pistols on the market, with an optional exclusive silencer upgrade.',
  'beretta-201t': 'A light sidearm favored by security professionals, capable of semi-auto burst fire.',
  'colt-america-l36': 'A cheap, easily concealed, nearly ubiquitous throwaway pistol.',
  'fichetti-security-600': 'A light sidearm with a thirty-round magazine, folding stock, and laser sight.',
  'taurus-omni-6': 'A rugged revolver with interchangeable cylinders that can fire either light or heavy pistol ammunition.',
  'ares-predator-v': 'The most popular heavy pistol in the world, with a built-in smartgun system.',
  'ares-viper-slivergun': 'A sleek flechette pistol pairing burst fire with an integral sound suppressor.',
  'browning-ultra-power': 'A tough, reliable heavy pistol with a built-in top-mounted laser sight.',
  'colt-government-2066': 'A government-issue pistol known for exceptional reliability, thanks to its electrically-fired, low-moving-parts design.',
  'remington-roomsweeper': 'Really a short-barreled shotgun disguised as a heavy pistol, devastating when loaded with flechette rounds.',
  'ruger-super-warhawk': 'A loud, flashy revolver — one of the scariest handguns around.',
  'ares-crusader-ii': 'A popular machine pistol with a large magazine, integral recoil compensation, and a smartgun system.',
  'ceska-black-scorpion': 'A classic concealable machine pistol with burst-fire and a folding stock.',
  'steyr-tmp': 'A lightweight polymer machine pistol capable of full auto, though hard to control at that rate.',
  'colt-cobra-tz-120': 'A popular SMG with a folding stock, laser sight, and barrel-mounted recoil compensation.',
  'fn-p93-praetor': 'A bullpup SMG purpose-built for elite fast-response teams, with an integrated stock and flashlight.',
  'hk-227': 'A corporate and military favorite SMG with a retractable stock, smartgun system, and integral suppressor.',
  'ingram-smartgun-x': 'The legendary street samurai’s SMG, kitted out with recoil compensation, a smartgun, and a suppressor.',
  'sck-model-100': 'The standard-issue SMG of Japanacorp security forces, with an internal smartgun and folding stock.',
  'uzi-iv': 'An aging but reliable SMG descendant of the famous Israeli original, with a folding stock and laser sight.',
  'ak-97': 'A legendary, famously reliable assault rifle that keeps working no matter what you put it through.',
  'ares-alpha': 'A best-selling assault rifle with an underbarrel grenade launcher, smartgun system, and strong recoil compensation.',
  'colt-m23': 'A cheap, mass-produced, no-frills assault rifle popular with gangers and modders alike.',
  'fn-har': 'A private-security favorite assault rifle with a laser sight and recoil compensation.',
  'yamaha-raiden': 'A state-of-the-art electronic-firing assault rifle with a built-in suppressor and smartgun system.',
  'ares-desert-strike': 'A combat-hardened long-range sniper rifle built to survive harsh environments.',
  'cavalier-arms-crockett-ebr': 'A hybrid assault/sniper rifle with burst-fire capability, trading magazine size for versatility.',
  'ranger-arms-sm-5': 'A legendary assassin’s sniper rifle that disassembles to fit in a briefcase, though its accuracy degrades in a firefight.',
  'remington-950': 'A classic bolt-action hunting rifle with a top-mounted scope, unable to mount underbarrel accessories.',
  'ruger-101': 'A futuristic gas-operated sporting rifle favored by professional hunters.',
  'defiance-t-250': 'A common semi-automatic shotgun with a backup pump action, available in normal or short-barreled form.',
  'enfield-as-7': 'A feared military assault shotgun offering massive close-quarters firepower.',
  'pjss-model-55': 'A precise, prestigious double-barreled sporting shotgun popular with European hunters and trap shooters.',
  'ares-siii-super-squirt': 'A non-lethal weapon firing chemical gel packs that deliver a toxin payload through the skin on contact.',
  'fichetti-pain-inducer': 'A non-lethal directed-energy weapon that inflicts agonizing, incapacitating pain without real damage.',
  'parashield-dart-pistol': 'The industry-standard dart pistol for delivering narcoject or other drug payloads.',
  'parashield-dart-rifle': 'A long-range dart rifle originally built for non-lethally taking down large game.',
  'ingram-valiant': 'A legendary, mercenary-favorite light machine gun with a stock, laser sight, and recoil compensation.',
  'stoner-ares-m202': 'A lightweight, hard-hitting medium machine gun popular as a secondary weapon on military vehicles.',
  'rpk-hmg': 'A heavy Russian machine gun typically fired from a tripod as vehicle-mounted support.',
  'ares-antioch-2': 'An affordable grenade launcher with a classic design and integral smartlink.',
  'armtech-mgl-12': 'A bullpup semi-automatic grenade launcher that carries more minigrenades than most competitors.',
  'aztechnology-striker': 'An extremely light, disposable missile launcher built for a single quick strike and a fast getaway.',
  'krime-cannon': 'A cheap, heavy assault cannon built with troll-scale modifications standard.',
  'onotari-interceptor': 'A military dual-barrel missile launcher that can load two different missiles or rockets at once.',
  'panther-xxl': 'A huge assault cannon firing small-tank-caliber ammunition, with a built-in smartgun system.',
  'grapple-gun': 'Fires a grappling hook and rope with an internal winch to pull it back — or pull you up.',
  'micro-flare-launcher': 'Fires signal flares that illuminate a wide area, or fire damage if aimed at a target.',
  'monofilament-chainsaw': 'A motorized saw with monofilament-edged teeth, built for cutting doors and barriers — too unwieldy to be a good melee weapon.',
}

const ARMOR_DESCRIPTIONS: Record<string, string> = {
  'actioneer-business-clothes': 'A discreetly armored power suit favored by Mr. Johnsons, faces, and fixers — includes a concealable holster in the jacket.',
  'armor-clothing': 'Lightweight ballistic fiber weave that’s almost impossible to spot as armor, though less protective than dedicated gear.',
  'armor-jacket': 'The most popular armor solution on the streets — solid protection without looking too conspicuous.',
  'armor-vest': 'A flexible-wrap vest worn under regular clothes without showing bulk — a cheap, popular option.',
  'chameleon-suit': 'A full-body suit with a smart camouflage coating that scans and mimics its surroundings, boosting Sneaking tests.',
  'full-body-armor': 'Heavy, impossible-to-conceal military-grade armor with tactical webbing and a modifiable helmet — built for serious ops, not subtlety.',
  'lined-coat': 'A Wild West-style armored duster, popular for decades, that also helps conceal items worn underneath.',
  'urban-explorer-jumpsuit': 'A breathable, colorful jumpsuit with surprisingly good lightweight armor, plus a built-in music player and biomonitor.',
  helmet: 'Head protection that adds to worn armor’s rating, with capacity for vision or audio accessories.',
  'ballistic-shield': 'A large SWAT-style shield with a viewing window and ladder-frame handle for scaling obstacles.',
  'riot-shield': 'A crowd-control shield that delivers an electrical shock to anyone touching it.',
}

const CYBERDECK_DESCRIPTIONS: Record<string, string> = {
  'erika-mcd-1': 'An entry-level cyberdeck — the cheapest way into the Matrix as a decker.',
  'microdeck-summit': 'A budget cyberdeck just a step up from entry-level gear.',
  'microtronica-azteca-200': 'A mid-tier cyberdeck balancing capability against cost.',
  'hermes-chariot': 'A solid mid-tier cyberdeck favored by working deckers.',
  'novatech-navigator': 'An upper mid-tier cyberdeck with real Matrix muscle.',
  'renraku-tsurugi': 'A high-end cyberdeck built for serious Matrix work.',
  'sony-ciy-720': 'A powerful, expensive cyberdeck for deckers who can afford the best.',
  'shiawase-cyber-5': 'A top-tier cyberdeck rivaling corporate-grade Matrix hardware.',
  'fairlight-excalibur': 'The best cyberdeck money can buy — bleeding-edge and priced accordingly.',
}

const GEAR_DESCRIPTIONS: Record<string, string> = {
  'diving-gear': 'Underwater diving equipment — suit, mask, air tank with two hours of air, and an inflatable ascent vest.',
  'maglock-passkey': 'A maglock skeleton key that fools a cardreader’s maglock into thinking a legitimate passkey was swiped.',
  'commlink-meta-link': 'An entry-level commlink — cheap and basic, but still a full Matrix-capable device.',
  'commlink-sony-emperor': 'A mid-tier commlink balancing price and performance.',
  'commlink-renraku-sensei': 'A solid commlink with room to run more demanding programs.',
  'commlink-erika-elite': 'A well-regarded, higher-end commlink favored by professionals.',
  'commlink-hermes-ikon': 'A capable commlink built for serious Matrix users.',
  'commlink-transys-avalon': 'A high-performance commlink for those who need real processing muscle.',
  'commlink-fairlight-caliban': 'A top-tier commlink — as good as commlinks get.',
  'commlink-sim-module': 'A commlink upgrade unlocking the full simsense/AR/VR experience, accessed through a direct neural interface.',
  'commlink-hot-sim-upgrade': 'A sim module modified for hot-sim, opening up the full — and dangerous — range of VR intensity.',
  'ar-gloves': 'Gloves that let you physically touch and manipulate virtual AR objects, with force feedback.',
  'biometric-reader': 'A handheld scanner for fingerprints, retina scans, voice, or tongue prints — used to lock devices to a specific person.',
  'electronic-paper': 'A foldable digital sheet that displays images, text, or video and doubles as a touchscreen.',
  printer: 'A full-color printer with an attached paper supply, for the rare occasion you need hardcopy.',
  'satellite-link': 'A portable satellite dish that connects to the Matrix from anywhere on Earth, even off the grid.',
  simrig: 'A simsense recorder that captures sensory and emotional experience data from its wearer for later playback.',
  'subvocal-mic': 'An adhesive throat microphone that lets you communicate via subvocalized, near-silent speech.',
  'trid-projector': 'Projects a trideo hologram into a five-meter cube — convincing, but rarely mistaken for the real thing.',
  trodes: 'A headband, net, or cap of electrodes giving a direct neural interface without needing implant surgery.',
  'rfid-standard-tags': 'Basic RFID tags used for geo-tagging, tracking, and identification on nearly every commercial product.',
  'rfid-datachip': 'A finger-sized chip for physically transferring large amounts of data — no wireless capability at all.',
  'rfid-security-tags': 'Tamper-resistant RFID tags corporations implant in employees or prisoners to monitor and track them.',
  'rfid-sensor-tags': 'An RFID tag paired with a small sensor that records data continuously for up to 24 hours.',
  'rfid-stealth-tags': 'A disguised, silent-running RFID tag with a Sleaze rating, hard to spot as a tag at all.',
  'bug-scanner': 'Locates and pinpoints wireless devices broadcasting nearby, including hidden bugs.',
  'data-tap': 'A hacking tool that clamps onto a data cable to tap the direct connection between whatever’s on either end.',
  headjammer: 'A jammer that attaches to the body to neutralize implanted commlinks and augmentation wireless signals.',
  'jammer-area': 'Floods a spherical area with electromagnetic noise, jamming wireless and radio devices within range.',
  'jammer-directional': 'Floods a narrow cone-shaped area with electromagnetic noise, jamming wireless and radio devices within it.',
  'micro-transceiver': 'A classic short-range voice communicator paired with an earbud and subvocal mic.',
  'tag-eraser': 'A handheld device that burns out RFID tags and other unshielded electronics at point-blank range.',
  'white-noise-generator': 'Floods an area with random noise, masking conversations from audio surveillance.',
  'agent-basic': 'An autonomous software agent that can act on your behalf on the Matrix, at a modest rating.',
  'agent-advanced': 'A more capable autonomous software agent for more demanding Matrix tasks.',
  'cyberprogram-common': 'A basic-use cyberprogram for cyberdecks handling everyday Matrix functions.',
  'cyberprogram-hacking': 'A cyberprogram built for offensive and defensive hacking work.',
  datasoft: 'A database of reference information on a specific subject, boosting related Knowledge Skill tests.',
  mapsoft: 'Detailed, self-updating map data for an area, aiding navigation and route-finding.',
  shopsoft: 'A shopping app with pricing and reviews for a category of goods, aiding buying and selling.',
  tutorsoft: 'A virtual private tutor that helps teach a specific mundane skill.',
  activesoft: 'A skillsoft replacing a physical Active skill, usable through a skillwire system.',
  knowsoft: 'A skillsoft replacing a Knowledge skill, overwriting the user’s own knowledge with its data.',
  linguasoft: 'A skillsoft that lets you speak a foreign language via chipped translation, accessed through a skilljack.',
  'credstick-standard': 'An anonymous, untraceable certified credstick holding up to 5,000¥.',
  'credstick-silver': 'An anonymous, untraceable certified credstick holding up to 20,000¥.',
  'credstick-gold': 'An anonymous, untraceable certified credstick holding up to 100,000¥.',
  'credstick-platinum': 'An anonymous, untraceable certified credstick holding up to 500,000¥.',
  'credstick-ebony': 'An anonymous, untraceable certified credstick holding up to 1,000,000¥.',
  'tool-kit': 'A portable set of tools for making standard repairs in a specific trade.',
  'tool-shop': 'A van-transportable set of advanced tools for building and repairing beyond what a kit can handle.',
  'tool-facility': 'A fixed, fully equipped workshop for the most advanced construction and modification work.',
  'binoculars-optical': 'Purely optical binoculars with built-in magnification — can’t take further vision enhancements.',
  'micro-camera': 'A tiny camera with minimal capacity for enhancements.',
  endoscope: 'A long fiber-optic cable for looking around corners, under doors, or into narrow spaces.',
  'imaging-scope': 'A weapon-mounted vision enhancer and display device.',
  periscope: 'An L-shaped optical tube for looking, shooting, or casting spells around a corner.',
  'mage-sight-goggles': 'Heavy goggles on a long fiber-optic cable, letting a magician peek around corners while casting.',
  binoculars: 'Electronic binoculars with built-in magnification and room for further vision enhancements.',
  camera: 'A visual recorder for stills, video, and trideo, upgradeable with vision and audio enhancements.',
  contacts: 'Nearly undetectable eye-worn displays with limited room for enhancements — wireless only, no data port.',
  glasses: 'Lightweight lens frames that can pass for ordinary eyewear while carrying vision enhancements.',
  goggles: 'Bulky head-strapped eyewear with plenty of room for vision enhancements.',
  monocle: 'A single-lens display worn on a headband, helmet arm, or old-fashioned chain.',
  'low-light-vision-enhancement': 'Lets you see normally in light as dim as starlight, though not in total darkness.',
  'flare-compensation-enhancement': 'Protects against blinding flashes and glare, reducing related vision penalties.',
  'image-link-enhancement': 'Displays AR visual information — text, images, video — directly in your field of vision.',
  'smartlink-enhancement': 'Works with a smartgun system to feed you range, ammo, and targeting data.',
  'thermographic-vision-enhancement': 'Lets you see in the infrared spectrum, spotting heat signatures even in total darkness.',
  'vision-enhancement': 'Sharpens visual acuity, adding to your limit on visual Perception tests.',
  'vision-magnification-enhancement': 'Digitally zooms vision up to fifty times for spotting distant targets.',
  'directional-microphone': 'Lets you eavesdrop on a distant conversation as if you were much closer.',
  earbuds: 'Ergonomic, hard-to-spot ear plugs that double as an audio device.',
  headphones: 'A full headset with more capacity for audio enhancements than earbuds, at the cost of being easier to spot.',
  'laser-microphone': 'Reads vibrations off a distant window or surface to reconstruct the sounds on the other side.',
  'omnidirectional-microphone': 'A standard all-directions audio pickup and recorder.',
  'audio-enhancement': 'Broadens your hearing to frequencies outside normal range and sharpens discrimination of subtle sounds.',
  'select-sound-filter': 'Lets you isolate and focus on specific sounds or patterns, filtering out the rest.',
  'spatial-recognizer': 'Pinpoints the direction a sound is coming from.',
  'handheld-sensor-housing': 'A small housing that can carry a handful of sensor functions in a portable form.',
  'wall-mounted-sensor-housing': 'A fixed housing for mounting sensors to a wall or structure.',
  'sensor-array': 'A bundled sensor package combining up to eight different sensor functions in one unit.',
  'single-sensor': 'A standalone sensor carrying a single chosen function, like motion detection or radiation.',
  'key-combination-lock': 'An old-fashioned mechanical key or combination lock, still found in odd corners of the Sixth World.',
  maglock: 'An electronic lock with configurable access control — biometrics, keycards, or passcodes.',
  'keypad-card-reader': 'An access-control reader for keycards or passcodes, paired with a maglock.',
  'anti-tamper-circuits': 'A security upgrade that detects and resists tampering attempts on a lock or device.',
  'restraint-metal': 'Standard metal restraints with a mechanical or wireless-controlled lock.',
  'restraint-plasteel': 'Flash-fused plasteel restraints that stay locked until physically cut free.',
  'restraint-plastic': 'Lightweight disposable plastic zip-tie restraints, easy to carry in bulk.',
  'restraint-containment-manacles': 'Metal restraints for wrists or ankles designed to prevent fast movement or use of implant weapons.',
  autopicker: 'A lockpick gun that speeds up bypassing mechanical locks.',
  'cellular-glove-molder': 'Molds a wearable print sleeve from a lifted finger or palm print to fool biometric locks.',
  'chisel-crowbar': 'A simple pry tool that doubles your effective Strength when forcing open a door or container.',
  'keycard-copier': 'Copies a stolen keycard in seconds, ready to be manufactured into a working duplicate.',
  'lockpick-set': 'A classic mechanical lockpicking toolkit, largely unchanged for centuries.',
  miniwelder: 'A portable electric-arc welder for cutting or joining metal, too small to double as a good weapon.',
  'miniwelder-fuel-canister': 'A replacement power supply for a miniwelder, good for about 30 minutes of use.',
  sequencer: 'An electronic device required to defeat keypad maglocks.',
  'glue-solvent': 'An aerosol solvent that dissolves about a square meter of fast-drying superglue.',
  'glue-sprayer': 'A fast-drying aerosol superglue that bonds two rigid surfaces together in about a Combat Turn.',
  'thermite-burning-bar': 'An incendiary rod-and-oxygen tool that melts through iron, steel, and even plasteel.',
  chemsuit: 'An impermeable coverall offering chemical protection — not a full hazmat seal, but solid protection over clothes or armor.',
  'climbing-gear': 'A backpack of rope, harness, gloves, and hardware needed for assisted climbing.',
  flashlight: 'A long-lasting, super-bright light, available in low-light and infrared versions.',
  'gas-mask': 'A re-breather mask giving immunity to inhalation-vector toxins, with an hour of clean air.',
  'gecko-tape-gloves': 'Gloves, kneepads, and slip-on soles with microscopic bonding hairs strong enough to stick a troll to a ceiling.',
  'hazmat-suit': 'A full-body suit with a four-hour air tank, providing a chemical seal against contact and inhaled toxins.',
  'light-stick': 'A snap-and-shake chemical light source giving three hours of soft illumination.',
  'magnesium-torch': 'A strike-and-burn torch giving five minutes of bright light.',
  'micro-flares': 'Colored signal flares fired to illuminate an area or mark a location.',
  'rappelling-gloves': 'Grippy gloves needed to safely handle ultrathin microwire rope without slicing your hands.',
  respirator: 'A filter mask protecting against inhalation-vector toxins.',
  'survival-kit': 'A rugged bag of camping and survival essentials — knife, fire starter, rations, water purifier, and more.',
  'catalyst-stick': 'A reusable chemical stick that crumbles treated stealth rope to dust on contact.',
  microwire: 'An ultra-thin, nearly monofilament climbing rope — hard to see, but dangerous to grip without special gloves.',
  'myomeric-rope': 'A remotely-controllable rope that can wind, snake around obstacles, or tie itself off.',
  'standard-rope': 'Ordinary climbing rope, rated to support a solid load.',
  'stealth-rope': 'Climbing rope that crumbles to untraceable dust when triggered with a catalyst stick.',
  biomonitor: 'A medical sensor that tracks vital signs and can alert others if you’re in trouble.',
  'disposable-syringe': 'A single-use syringe for administering an injected drug or toxin dose.',
  medkit: 'A rated medical kit supporting First Aid and Medicine tests in the field.',
  'medkit-supplies': 'Replacement consumables for a medkit after its supplies run out.',
  'docwagon-basic': 'The entry-level DocWagon contract — a private emergency medical response team on call for a year.',
  'docwagon-gold': 'A mid-tier DocWagon contract with faster, better-equipped emergency medical response.',
  'docwagon-platinum': 'A premium DocWagon contract with priority, high-quality emergency medical response.',
  'docwagon-super-platinum': 'The top-tier DocWagon contract — the fastest, best-equipped emergency medical response money can buy.',
  'antidote-patch': 'A slap patch delivering a dose of antidote to counter a poison already in the system.',
  'chem-patch': 'A slap patch delivering a chosen chemical dose through the skin.',
  'stim-patch': 'A slap patch delivering a stimulant dose to keep you going.',
  'tranq-patch': 'A slap patch delivering a sedative dose to calm or subdue.',
  'trauma-patch': 'A slap patch that stabilizes a badly wounded patient in the field.',
  'magical-lodge-materials': 'Consumable materials used to assemble a temporary magical lodge for rituals.',
  reagents: 'Raw magical material spent to power enchanting, rituals, and alchemical preparations.',
  'spell-formula-combat': 'A recorded formula for preparing an alchemical version of a Combat spell.',
  'spell-formula-detection': 'A recorded formula for preparing an alchemical version of a Detection spell.',
  'spell-formula-health': 'A recorded formula for preparing an alchemical version of a Health spell.',
  'spell-formula-illusion': 'A recorded formula for preparing an alchemical version of an Illusion spell.',
  'spell-formula-manipulation': 'A recorded formula for preparing an alchemical version of a Manipulation spell.',
  'fake-sin': 'A forged system identification number, letting a SINless character pass as a legitimate citizen — until it’s traced.',
  'fake-license': 'A forged permit tied to a fake SIN, letting the holder legally carry a Restricted item — on paper, anyway.',
}

const RESOURCE_CATEGORY_DESCRIPTIONS: Record<string, string> = {
  armor: 'Wearable protection that adds an Armor rating to resist physical and stun damage.',
  survival: 'Basic gear for enduring the field — camping, exposure, and staying alive rough.',
  'breaking-and-entering': 'Tools for bypassing locks, doors, and physical security without setting off alarms.',
  blades: 'Melee weapons that deal damage in close combat via cutting or stabbing.',
  clubs: 'Blunt melee weapons for close combat.',
  'other-melee': 'Miscellaneous close-combat weapons outside the standard blade/club categories.',
  bows: 'Silent ranged weapons using drawn tension to fire arrows.',
  crossbows: 'Ranged weapons that fire bolts, quieter than firearms.',
  'throwing-weapons': 'Weapons thrown by hand at a target.',
  tasers: 'Non-lethal ranged weapons delivering an electrical shock.',
  'hold-outs': 'Tiny, easily concealed pistols with limited range and stopping power.',
  'light-pistols': 'Compact, easily concealed handguns with modest damage.',
  'heavy-pistols': 'Handguns trading concealability for more stopping power.',
  'machine-pistols': 'Compact automatic handguns capable of burst or full-auto fire.',
  'submachine-guns': 'Compact automatic weapons for close-range volume of fire.',
  'assault-rifles': 'Versatile automatic rifles balancing range, damage, and rate of fire.',
  'sniper-rifles': 'Long-range rifles built for precision single shots.',
  shotguns: 'Short-range weapons firing a spread or heavy single round.',
  'special-weapons': 'Unconventional heavy or exotic firearms outside the usual categories.',
  'machine-guns': 'Sustained-fire weapons built for heavy suppressive volume.',
  'cannons-launchers': 'Heavy ordnance delivering explosive or anti-vehicle firepower.',
  bike: 'A two-wheeled ground vehicle, fast and maneuverable but exposed.',
  car: 'A standard passenger ground vehicle.',
  'truck-van': 'A larger ground vehicle with more cargo or passenger capacity.',
  boat: 'A surface watercraft.',
  submarine: 'An underwater vehicle.',
  aircraft: 'A vehicle capable of flight.',
  drone: 'An unpiloted vehicle operated remotely or autonomously.',
  cyberdeck: 'A dedicated Matrix rig used by deckers to run and hack the grid.',
  commlink: 'A personal Matrix device handling comms, apps, and the character’s persona.',
  'electronics-accessory': 'Add-on electronics that extend or support other devices.',
  'rfid-tag': 'A small wireless identity or tracking chip readable by nearby devices.',
  communications: 'Gear for secure or covert communication and countermeasures against being overheard.',
  software: 'Programs and utilities that run on a commlink or deck.',
  skillsoft: 'A chip or program that grants temporary access to a skill.',
  credstick: 'A physical store of nuyen, usable for transactions.',
  tools: 'Hand tools supporting a trade or technical skill.',
  'optical-imaging': 'Vision-enhancing or vision-recording devices.',
  'security-device': 'Gear used to secure, monitor, or protect a location.',
  restraint: 'Gear used to bind or immobilize a target.',
  'industrial-chemical': 'A chemical agent with a practical, often hazardous, industrial use.',
  'grapple-gun-gear': 'Gear supporting climbing and grappling maneuvers.',
  biotech: 'Medical and biological support gear for treating injuries.',
  'docwagon-contract': 'An emergency medical response contract that dispatches a trauma team.',
  'slap-patch': 'A single-use adhesive patch delivering a drug or medical effect.',
  'magical-supplies': 'Consumable materials used to support magical practice.',
  formula: 'A recorded spell formula used to prepare alchemical items.',
  'audio-device': 'A device for recording, transmitting, or manipulating sound.',
  identity: 'Gear related to establishing or supporting a false identity.',
  'sensor-device': 'A standalone sensor for detecting people, objects, or activity.',
}

function lookup(dictionary: Record<string, string>, id: string, fallback: string): string {
  return dictionary[id] ?? fallback
}

export function describeAttribute(id: string): string {
  return lookup(ATTRIBUTE_DESCRIPTIONS, id, 'A core attribute used to build dice pools for related tests.')
}

export function describeQuality(id: string): string {
  return lookup(QUALITY_DESCRIPTIONS, id, 'A creation-time quality with a fixed Karma cost.')
}

export function describePath(kind: string): string {
  return lookup(PATH_DESCRIPTIONS, kind, 'An awakened or resonant path with its own grants and restrictions.')
}

export function describeTradition(id: string): string {
  return lookup(TRADITION_DESCRIPTIONS, id, 'A magical tradition setting the drain attribute and allowed spirit list.')
}

export function describeAspectedValue(id: string): string {
  return lookup(ASPECTED_VALUE_DESCRIPTIONS, id, 'The single magical skill group an aspected magician has access to.')
}

export function describeMentorSpirit(id: string): string {
  return lookup(MENTOR_SPIRIT_DESCRIPTIONS, id, 'A mentor spirit offering narrow bonuses tied to its themes.')
}

export function describeAdeptPower(id: string): string {
  return lookup(ADEPT_POWER_DESCRIPTIONS, id, 'An adept power purchased with Power Points.')
}

export function describeRitual(id: string): string {
  return lookup(RITUAL_DESCRIPTIONS, id, 'A group ritual built on an underlying spell.')
}

export function describeComplexForm(id: string): string {
  return lookup(COMPLEX_FORM_DESCRIPTIONS, id, 'A technomancer complex form threaded live from Resonance.')
}

export function describeSpell(spell: { id: string; category: string; type: string }): string {
  const specific = SPELL_DESCRIPTIONS[spell.id]
  if (specific) return specific
  const categoryText = SPELL_CATEGORY_DESCRIPTIONS[spell.category] ?? 'A spell with an effect defined by its category.'
  const typeText = SPELL_TYPE_DESCRIPTIONS[spell.type] ?? ''
  return typeText ? `${categoryText} ${typeText}` : categoryText
}

export function describeSkillDomain(domain: string): string {
  return lookup(SKILL_DOMAIN_DESCRIPTIONS, domain, 'A skill used to resolve related tests.')
}

export function describeAugmentationCategory(categoryId: string): string {
  return lookup(AUGMENTATION_CATEGORY_DESCRIPTIONS, categoryId, 'A cyberware or bioware augmentation.')
}

export function describeAugmentation(id: string, categoryId: string): string {
  return AUGMENTATION_DESCRIPTIONS[id] ?? describeAugmentationCategory(categoryId)
}

export function describeResourceCategory(groupKey: string): string {
  return lookup(RESOURCE_CATEGORY_DESCRIPTIONS, groupKey, 'Gear available for purchase during creation.')
}

export function describeResourceItem(id: string, groupKey: string): string {
  return GEAR_DESCRIPTIONS[id] ?? WEAPON_DESCRIPTIONS[id] ?? ARMOR_DESCRIPTIONS[id] ?? VEHICLE_DESCRIPTIONS[id] ?? CYBERDECK_DESCRIPTIONS[id] ?? describeResourceCategory(groupKey)
}
