// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeattleByNight.Infrastructure.Persistence;

#nullable disable

namespace SeattleByNight.Infrastructure.Migrations
{
    [DbContext(typeof(SeattleByNightDbContext))]
    [Migration("20260831155153_AddRoomContentAndDiscovery")]
    partial class AddRoomContentAndDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_normalized_name");

                    b.ToTable("asp_net_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("asp_net_user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("asp_net_user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("asp_net_user_tokens", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.AuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("target_type");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId")
                        .HasDatabaseName("ix_audit_records_actor_user_id");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("ix_audit_records_created_at_utc_id");

                    b.HasIndex("TargetType", "TargetId")
                        .HasDatabaseName("ix_audit_records_target");

                    b.ToTable("audit_records", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CurrentRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_room_id");

                    b.Property<DateTimeOffset?>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at_utc");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRoomId")
                        .HasDatabaseName("ix_characters_current_room_id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_normalized_name");

                    b.HasIndex("UserId", "LifecycleState")
                        .HasDatabaseName("ix_characters_user_id_lifecycle_state");

                    b.ToTable("characters", null, t =>
                        {
                            t.HasCheckConstraint("ck_characters_lifecycle_finalized_at", "(lifecycle_state = 'Draft' AND finalized_at_utc IS NULL) OR (lifecycle_state = 'Finalized' AND finalized_at_utc IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterActionReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "RequestId")
                        .IsUnique();

                    b.ToTable("character_action_receipts", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterActiveEffect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("DurationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("duration_type");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_id");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<string>("StackingGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("stacking_group");

                    b.Property<string>("StackingRule")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("stacking_rule");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_character_active_effects_character");

                    b.ToTable("character_active_effects", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterAdvancement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("catalog_version");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("details");

                    b.Property<int>("KarmaCost")
                        .HasColumnType("integer")
                        .HasColumnName("karma_cost");

                    b.Property<int?>("NewValue")
                        .HasColumnType("integer")
                        .HasColumnName("new_value");

                    b.Property<int?>("PreviousValue")
                        .HasColumnType("integer")
                        .HasColumnName("previous_value");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ruleset_id");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "CreatedAtUtc");

                    b.ToTable("character_advancements", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_advancements_karma_cost", "karma_cost >= 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterCareerState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<int>("CareerDocumentSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("career_document_schema_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentKarma")
                        .HasColumnType("integer")
                        .HasColumnName("current_karma");

                    b.Property<int>("CurrentNuyen")
                        .HasColumnType("integer")
                        .HasColumnName("current_nuyen");

                    b.Property<int>("LifetimeKarmaEarned")
                        .HasColumnType("integer")
                        .HasColumnName("lifetime_karma_earned");

                    b.Property<string>("ProgressionJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("progression");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("CharacterId");

                    b.ToTable("character_career_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_career_states_nonnegative", "current_karma >= 0 AND current_nuyen >= 0 AND lifetime_karma_earned >= 0");

                            t.HasCheckConstraint("ck_character_career_states_schema_version", "career_document_schema_version > 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterCreationDraft", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("CatalogSemanticDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_semantic_digest");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("catalog_version");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("CreationMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creation_method_id");

                    b.Property<int>("DocumentSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("document_schema_version");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ruleset_id");

                    b.Property<string>("SelectionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("selections");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("CharacterId");

                    b.ToTable("character_creation_drafts", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_creation_drafts_digest", "length(catalog_semantic_digest) = 64");

                            t.HasCheckConstraint("ck_character_creation_drafts_document_schema_version", "document_schema_version > 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterDiscovery", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("DiscoveredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovered_at_utc");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subject_type");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "SubjectType", "SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_character_discoveries_character_subject");

                    b.ToTable("character_discoveries", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acquired_at_utc");

                    b.Property<string>("AcquisitionSource")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("acquisition_source");

                    b.Property<string>("CatalogCollection")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_collection");

                    b.Property<string>("CatalogItemId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("catalog_item_id");

                    b.Property<string>("CatalogSemanticDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_semantic_digest");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("catalog_version");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters");

                    b.Property<int>("PurchasePriceNuyen")
                        .HasColumnType("integer")
                        .HasColumnName("purchase_price_nuyen");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ruleset_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "AcquiredAtUtc");

                    b.ToTable("character_inventory_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_inventory_items_digest", "length(catalog_semantic_digest) = 64");

                            t.HasCheckConstraint("ck_character_inventory_items_price", "purchase_price_nuyen >= 0");

                            t.HasCheckConstraint("ck_character_inventory_items_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterResourceTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdvancementId")
                        .HasColumnType("uuid")
                        .HasColumnName("advancement_id");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("integer")
                        .HasColumnName("balance_after");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_item_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("resource_type");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("AdvancementId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("CharacterId", "CreatedAtUtc");

                    b.ToTable("character_resource_transactions", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_resource_transactions_balance", "balance_after >= 0");

                            t.HasCheckConstraint("ck_character_resource_transactions_single_reference", "NOT (advancement_id IS NOT NULL AND inventory_item_id IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterRuntimeState", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("CurrentEdge")
                        .HasColumnType("integer")
                        .HasColumnName("current_edge");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("integer")
                        .HasColumnName("physical_damage");

                    b.Property<int>("StunDamage")
                        .HasColumnType("integer")
                        .HasColumnName("stun_damage");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("CharacterId");

                    b.ToTable("character_runtime_states", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_runtime_states_nonnegative", "physical_damage >= 0 AND stun_damage >= 0 AND current_edge >= 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterSheet", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("CanonicalSheetJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("canonical_sheet");

                    b.Property<string>("CatalogSemanticDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("catalog_semantic_digest");

                    b.Property<string>("CatalogVersion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("catalog_version");

                    b.Property<string>("CreationMethodId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("creation_method_id");

                    b.Property<DateTimeOffset>("FinalizedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at_utc");

                    b.Property<string>("RulesetId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ruleset_id");

                    b.Property<int>("SheetSchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("sheet_schema_version");

                    b.Property<string>("SourceDraftDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_draft_digest");

                    b.HasKey("CharacterId");

                    b.ToTable("character_sheets", null, t =>
                        {
                            t.HasCheckConstraint("ck_character_sheets_digests", "length(catalog_semantic_digest) = 64 AND length(source_draft_digest) = 64");

                            t.HasCheckConstraint("ck_character_sheets_schema_version", "sheet_schema_version > 0");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Say")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("RoomId", "CreatedAtUtc")
                        .HasDatabaseName("ix_chat_messages_room_id_created_at_utc");

                    b.ToTable("chat_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_chat_messages_type", "type IN ('Say','Emote','Roll')");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.GameTestAuditRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ResultJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("result");

                    b.Property<long>("RngSeed")
                        .HasColumnType("bigint")
                        .HasColumnName("rng_seed");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("test_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId", "CreatedAtUtc")
                        .HasDatabaseName("ix_game_test_audit_records_character_created");

                    b.ToTable("game_test_audit_records", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.NpcInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Awareness")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("awareness");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PhysicalDamage")
                        .HasColumnType("integer")
                        .HasColumnName("physical_damage");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<int>("StunDamage")
                        .HasColumnType("integer")
                        .HasColumnName("stun_damage");

                    b.Property<string>("TemplateId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("template_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_npc_instances_room");

                    b.ToTable("npc_instances", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.PlaySession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at_utc");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at_utc");

                    b.Property<DateTimeOffset>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_activity_utc");

                    b.Property<DateTimeOffset>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .HasDatabaseName("ix_play_sessions_character_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_play_sessions_user_id_active")
                        .HasFilter("ended_at_utc IS NULL");

                    b.ToTable("play_sessions", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("description");

                    b.Property<int>("MapLayer")
                        .HasColumnType("integer")
                        .HasColumnName("map_layer");

                    b.Property<int>("MapX")
                        .HasColumnType("integer")
                        .HasColumnName("map_x");

                    b.Property<int>("MapY")
                        .HasColumnType("integer")
                        .HasColumnName("map_y");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MapLayer", "MapX", "MapY")
                        .IsUnique()
                        .HasDatabaseName("ux_rooms_map_layer_map_x_map_y");

                    b.ToTable("rooms", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomExit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("DestinationRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("destination_room_id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("direction");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_locked");

                    b.Property<Guid>("SourceRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_room_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DestinationRoomId")
                        .HasDatabaseName("ix_room_exits_destination_room_id");

                    b.HasIndex("SourceRoomId", "Direction")
                        .IsUnique()
                        .HasDatabaseName("ux_room_exits_source_room_id_direction");

                    b.ToTable("room_exits", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_exits_direction", "direction IN ('north','northeast','east','southeast','south','southwest','west','northwest','up','down')");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomInteractable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<int>("DiscoveryThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("discovery_threshold");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("boolean")
                        .HasColumnName("is_hidden");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_interactables_room");

                    b.ToTable("room_interactables", (string)null);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomVisit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EnteredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entered_at_utc");

                    b.Property<DateTimeOffset?>("LeftAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at_utc");

                    b.Property<Guid>("PlaySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("play_session_id");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.HasKey("Id");

                    b.HasIndex("PlaySessionId")
                        .IsUnique()
                        .HasDatabaseName("ix_room_visits_play_session_id_open")
                        .HasFilter("left_at_utc IS NULL");

                    b.HasIndex("RoomId", "EnteredAtUtc")
                        .HasDatabaseName("ix_room_visits_room_id_entered_at_utc");

                    b.HasIndex("PlaySessionId", "RoomId", "EnteredAtUtc", "LeftAtUtc")
                        .HasDatabaseName("ix_room_visits_transcript_visibility");

                    b.ToTable("room_visits", null, t =>
                        {
                            t.HasCheckConstraint("ck_room_visits_interval", "left_at_utc IS NULL OR left_at_utc >= entered_at_utc");
                        });
                });

            modelBuilder.Entity("SeattleByNight.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_email");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_users_normalized_user_name");

                    b.ToTable("asp_net_users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.AuditRecord", b =>
                {
                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.Character", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("CurrentRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterActionReceipt", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterActiveEffect", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterAdvancement", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterCareerState", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithOne()
                        .HasForeignKey("SeattleByNight.Domain.Entities.CharacterCareerState", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterCreationDraft", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithOne()
                        .HasForeignKey("SeattleByNight.Domain.Entities.CharacterCreationDraft", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterDiscovery", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterInventoryItem", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterResourceTransaction", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.CharacterAdvancement", null)
                        .WithMany()
                        .HasForeignKey("AdvancementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Domain.Entities.CharacterInventoryItem", null)
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterRuntimeState", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithOne()
                        .HasForeignKey("SeattleByNight.Domain.Entities.CharacterRuntimeState", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.CharacterSheet", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithOne()
                        .HasForeignKey("SeattleByNight.Domain.Entities.CharacterSheet", "CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.GameTestAuditRecord", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.NpcInstance", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.PlaySession", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomExit", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("DestinationRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("SourceRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomInteractable", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SeattleByNight.Domain.Entities.RoomVisit", b =>
                {
                    b.HasOne("SeattleByNight.Domain.Entities.PlaySession", null)
                        .WithMany()
                        .HasForeignKey("PlaySessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeattleByNight.Domain.Entities.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
